using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AudioManager : MonoBehaviour
{
    public static AudioManager Instance;

    public AudioSource musicSource;
    public AudioSource sfxSource;

    public AudioClip overworldMusic;
    public AudioClip caveMusic;

    public AudioClip[] variousSFX;
    // Start is called before the first frame update
    void Start()
    {
        musicSource.clip = overworldMusic;
        musicSource.Play();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    void Awake()
    {
        //make sure the game has only one audio manager throughout 
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else Destroy(gameObject);
    }
    public void PlayMusicSFX(AudioClip Clip)
    {
        sfxSource.clip = Clip;
        sfxSource.Play();
    }
    public void PlayMusic(AudioClip Clip)
    {
        musicSource.clip = Clip;
        musicSource.Play();
    }
    public void PlayRandomSFX(params AudioClip[] clips)
    {
        variousSFX = clips;
        int index = Random.Range(0, variousSFX.Length);
        sfxSource.PlayOneShot(variousSFX[index]);
    }
}
